### ISSUE TITLE
No output if regex fails

### ISSUE THREAD

**Issue by punkrokk** [DavidJBianco/pycef#11]
* If regex fails, return None, not an empty dict. More pythonic, easier to handle when calling function
* add null logger, and some logger output
* add some end user help to tell them that regex failed, instead of returning empty dict { }

**Comment by DavidJBianco** [comment]
Thanks, @punkrokk.  I tweaked these a tiny bit and merged them into MASTER just now.  Should be hitting PyPi soon.
