### ISSUE TITLE
Wrong key 'DeviceName', should be 'Name' according to spec

### ISSUE THREAD

**Issue by kfearos** [DavidJBianco/pycef#14]
https://www.elastic.co/guide/en/beats/filebeat/master/exported-fields-cef.html

```
cef.name
Short description of the event.

type: keyword
```

**Comment by DavidJBianco** [comment]
Thanks, I think the best way to address this is to keep the _DeviceName_ key as it is (for compatibility) and add a new _Name_ key with the same value.  I'll just replace _DeviceName_ with _Name_ in the documentation.  

Also, for my own reference later, here's the actual CEF format specification: https://community.microfocus.com/t5/ArcSight-Connectors/ArcSight-Common-Event-Format-CEF-Implementation-Standard/ta-p/1645557

**Comment by DavidJBianco** [comment]
This is fixed in 7fe1b00 and published as v1.11.
