### ISSUE TITLE
Remove header parsing anchor to support CEF via syslog

### ISSUE THREAD

**Issue by punkrokk** [DavidJBianco/pycef#9]
@DavidJBianco Hey dude!

Great little python script :)

So - my use case is exactly what you created this for with one exception. If I am getting a cef payload from a syslog file or stream, I have a few fields of syslog before the beginning of the CEF string.

For example, notice below in **bold** my CEF syslog line has a date and hostname, as possible in a syslog packet. 

```
**Nov 17 02:14:39 arcsightfwd.davidbianco.io** CEF:0|ACME|Firewall X|||Accept|Unknown| eventId=187643083 mrt=1541908269348 proto=UDP in=1200 out=1200 modelConfidence=4 severity=0 relevance=10 assetCriticality=0 priority=2 art=1542420847090 act=Allow rt=1542420847090 src=192.168.30.15 sourceZoneID=M-fU32AABABCDVFpYAT3UdQ\=\= sourceZoneURI=/All Zones/ArcSight System/Private Address Space Zones/RFC1918: 192.168.0.0-192.168.255.255 spt=32488 slong=0.0 slat=0.0 ... <more payload here>
```

It's my assessment that in your CEF header parsing regex, it works fine with out the ^ anchoring us to the beginning of the string. 

Replace the current [line 19](https://github.com/DavidJBianco/pycef/blob/f3c12d0b0c19ff5d32899e1418feed364d14c14f/pycef/__init__.py#L19)

with: 

`header_re = r'((CEF:\d+)([^=\\]+\|){,7})(.*)'`

This still works exactly as intended, but doesn't fail if I'm trying to read in syslog lines. :)

**Comment by DavidJBianco** [comment]
Good catch, thanks!  This is merged.
